AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodePipeline for ECS Blue-Green Deployment'

Parameters:
  AppName:
    Type: String
    Default: 'java-full-stack'
  DeploymentTimestamp:
    Type: String
    Default: "default"

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AppName}-Pipeline
      RoleArn: !ImportValue 
        Fn::Sub: '${AppName}-CodePipelineServiceRoleArn'
      ArtifactStore:
        Type: S3
        Location: !ImportValue 
          Fn::Sub: '${AppName}-ArtifactBucketName'
      Stages:
        - Name: Source
          Actions:
            - Name: S3-Artifacts-Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: '1'
                Provider: S3
              Configuration:
                S3Bucket: !ImportValue 
                  Fn::Sub: '${AppName}-ArtifactBucketName'
                S3ObjectKey: deployment-artifacts/latest.zip
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: ECS-Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CodeDeployToECS
              Configuration:
                ApplicationName: !ImportValue 
                  Fn::Sub: '${AppName}-CodeDeployAppName'
                DeploymentGroupName: !ImportValue 
                  Fn::Sub: '${AppName}-CodeDeployDeploymentGroupName'
                TaskDefinitionTemplateArtifact: SourceArtifact
                TaskDefinitionTemplatePath: "taskdef.json"
                AppSpecTemplateArtifact: SourceArtifact
                AppSpecTemplatePath: "appspec.yml"
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

Outputs:
  PipelineName:
    Value: !Ref CodePipeline
    Export:
      Name: !Sub ${AppName}-PipelineName
  # DeploymentTimestamp:
  #   Value: !Ref DeploymentTimestamp
  #   Export:
  #     Name: !Sub ${AppName}-DeploymentTimestamp